# Generated by Django 3.1.2 on 2021-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=20)),
                ('alloy', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
