# Generated by Django 3.1.2 on 2021-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(max_length=16)),
                ('counterParty', models.CharField(max_length=100)),
                ('contractCounterParty', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('alloy', models.TextField()),
                ('minVol', models.IntegerField()),
                ('maxVol', models.IntegerField()),
                ('lastChangeUser', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=20)),
                ('alloy', models.CharField(max_length=10)),
                ('shape', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
