# Generated by Django 3.1.2 on 2021-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='lastChangeUser',
        ),
        migrations.AlterField(
            model_name='contract',
            name='alloy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
