# Generated by Django 3.1.2 on 2021-01-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210106_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(max_length=16)),
                ('isPurchase', models.BooleanField(default=False)),
                ('counterParty', models.TextField()),
                ('product', models.CharField(max_length=50)),
                ('alloy', models.TextField()),
                ('shape', models.CharField(max_length=10)),
                ('isRange', models.BooleanField(default=False)),
                ('minVol', models.IntegerField()),
                ('maxVol', models.IntegerField()),
                ('originSupplier', models.TextField()),
                ('allocationCtr', models.CharField(max_length=16)),
            ],
        ),
    ]
