# Generated by Django 3.1.2 on 2021-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='counterParty',
            field=models.CharField(max_length=50),
        ),
    ]
