# Generated by Django 3.1.2 on 2021-03-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='shape',
            field=models.CharField(max_length=50),
        ),
    ]
