# Generated by Django 3.1.2 on 2021-03-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210330_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='maxVol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='minVol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='originSupplier',
            field=models.CharField(max_length=50),
        ),
    ]
